approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  eslint@*:
    dependencies:
      globals: ^16.0.0
  usehooks-ts@*:
    dependencies:
      react: ^19.0.0
    peerDependencies:
      react: ^19.0.0
