compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:  
  "usehooks-ts@*":
    dependencies:
      "react": "^19.0.0"
    peerDependencies:
      "react": "^19.0.0"
  "eslint@*":
    dependencies:
      "globals": "^16.0.0"
